package io.vertigo.ai.server.models;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Score implements DtObject {
	private static final long serialVersionUID = 1L;

	private java.math.BigDecimal scoreMean;
	private java.math.BigDecimal scoreStd;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Score Mean'.
	 * @return BigDecimal scoreMean <b>Obligatoire</b>
	 */
	@Field(smartType = "STyDecimalAIResponse", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Score Mean")
	public java.math.BigDecimal getScoreMean() {
		return scoreMean;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Score Mean'.
	 * @param scoreMean BigDecimal <b>Obligatoire</b>
	 */
	public void setScoreMean(final java.math.BigDecimal scoreMean) {
		this.scoreMean = scoreMean;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Score Standard deviation'.
	 * @return BigDecimal scoreStd <b>Obligatoire</b>
	 */
	@Field(smartType = "STyDecimalAIResponse", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Score Standard deviation")
	public java.math.BigDecimal getScoreStd() {
		return scoreStd;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Score Standard deviation'.
	 * @param scoreStd BigDecimal <b>Obligatoire</b>
	 */
	public void setScoreStd(final java.math.BigDecimal scoreStd) {
		this.scoreStd = scoreStd;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
