package io.vertigo.ai.example.telstra.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
@io.vertigo.datamodel.structure.stereotype.DataSpace("train")
public final class LocationTrain implements Entity {
	private static final long serialVersionUID = 1L;

	private Long id;
	private Integer code;
	private String location;
	private Integer severityFault;

	/** {@inheritDoc} */
	@Override
	public UID<LocationTrain> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'ID'.
	 * @return Long id <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "ID")
	public Long getId() {
		return id;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'ID'.
	 * @param id Long <b>Obligatoire</b>
	 */
	public void setId(final Long id) {
		this.id = id;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Code'.
	 * @return Integer code
	 */
	@Field(smartType = "STyInteger", label = "Code")
	public Integer getCode() {
		return code;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Code'.
	 * @param code Integer
	 */
	public void setCode(final Integer code) {
		this.code = code;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Location'.
	 * @return String location <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Location")
	public String getLocation() {
		return location;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Location'.
	 * @param location String <b>Obligatoire</b>
	 */
	public void setLocation(final String location) {
		this.location = location;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Severity Fault'.
	 * @return Integer severityFault <b>Obligatoire</b>
	 */
	@Field(smartType = "STyInteger", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Severity Fault")
	public Integer getSeverityFault() {
		return severityFault;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Severity Fault'.
	 * @param severityFault Integer <b>Obligatoire</b>
	 */
	public void setSeverityFault(final Integer severityFault) {
		this.severityFault = severityFault;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
