version: "3.9"

services:

    ihm:
      image: "ihm:latest"
      ports:
        - "8080:8080"
    api:
      build: ./predict-server
      command: python ./scripts/manage.py runserver
      ports:
        - "8000:8000"