version: "3.9"

services:

    ihm:
      image: "vertigo-ai-ihm:latest"
      build: ./vertigo-ai-ihm
      hostname: vertigo-ai-ihm
      ports:
        - "8080:80"
    api:
      image: "predict-server:latest"
      build: ./predict-server
      hostname: ai-predict-api
      environment: 
        - ALLOWED_HOSTS=ai-predict-api
        - DJANGO_SETTINGS_MODULE=AIPredict.settings.development
      ports:
        - "8000:8000"

