package io.vertigo.ai.predict.models;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Explanation implements DtObject {
	private static final long serialVersionUID = 1L;

	private java.util.List<java.math.BigDecimal> explainFeature = new java.util.ArrayList<>();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Feature Explanation'.
	 * @return List de BigDecimal explainFeature
	 */
	@Field(smartType = "STyPredictionNumeric", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Feature Explanation")
	public java.util.List<java.math.BigDecimal> getExplainFeature() {
		return explainFeature;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Feature Explanation'.
	 * @param explainFeature List de BigDecimal
	 */
	public void setExplainFeature(final java.util.List<java.math.BigDecimal> explainFeature) {
		io.vertigo.core.lang.Assertion.check().isNotNull(explainFeature);
		//---
		this.explainFeature = explainFeature;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
