package io.vertigo.ai.predict.models;

import java.util.ArrayList;
import java.util.List;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class PredictResponse implements DtObject {
	private static final long serialVersionUID = 1L;

	private List<io.vertigo.ai.predict.models.Predict> predictionList =  new ArrayList<io.vertigo.ai.predict.models.Predict>();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction list'.
	 * @return DtList de Predict predictionList
	 */
	@Field(smartType = "STyDtPredict", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Prediction list")
	public List<Predict> getPredictionList() {
		return predictionList;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction list'.
	 * @param predictionList DtList de Predict
	 */
	public void setPredictionList(final   List<Predict> predictionList) {
		io.vertigo.core.lang.Assertion.check().isNotNull(predictionList);
		//---
		this.predictionList = predictionList;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}

}
