package io.vertigo.ai.predict.models;

import java.util.ArrayList;
import java.util.List;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Predict implements DtObject {
	private static final long serialVersionUID = 1L;

	private String predictionLabel;
	private java.math.BigDecimal predictionNumeric;
	private java.util.List<java.math.BigDecimal> predictionVector = new java.util.ArrayList<>();
	private java.util.List<java.math.BigDecimal> predictionProba = new java.util.ArrayList<>();
	private List<List<Double>> explanation2D =  new ArrayList<List<Double>>();
	private java.util.List<java.math.BigDecimal> explanation1D = new java.util.ArrayList<>();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction Label'.
	 * @return String predictionLabel
	 */
	@Field(smartType = "STyPredictionLabel", label = "Prediction Label")
	public String getPredictionLabel() {
		return predictionLabel;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction Label'.
	 * @param predictionLabel String
	 */
	public void setPredictionLabel(final String predictionLabel) {
		this.predictionLabel = predictionLabel;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Numeric Prediction'.
	 * @return BigDecimal predictionNumeric
	 */
	@Field(smartType = "STyPredictionNumeric", label = "Numeric Prediction")
	public java.math.BigDecimal getPredictionNumeric() {
		return predictionNumeric;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Numeric Prediction'.
	 * @param predictionNumeric BigDecimal
	 */
	public void setPredictionNumeric(final java.math.BigDecimal predictionNumeric) {
		this.predictionNumeric = predictionNumeric;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Vector Prediction'.
	 * @return List de BigDecimal predictionVector
	 */
	@Field(smartType = "STyPredictionNumeric", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Prediction Probability")
	public java.util.List<java.math.BigDecimal> getPredictionVector() {
		return predictionVector;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Vector Prediction'.
	 * @param predictionVector List de BigDecimal
	 */
	public void setPredictionVector(final java.util.List<java.math.BigDecimal> predictionVector) {
		io.vertigo.core.lang.Assertion.check().isNotNull(predictionVector);
		//---
		this.predictionVector = predictionVector;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction Probability'.
	 * @return List de BigDecimal predictionProba
	 */
	@Field(smartType = "STyPredictionNumeric", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Prediction Probability")
	public java.util.List<java.math.BigDecimal> getPredictionProba() {
		return predictionProba;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction Probability'.
	 * @param predictionProba List de BigDecimal
	 */
	public void setPredictionProba(final java.util.List<java.math.BigDecimal> predictionProba) {
		io.vertigo.core.lang.Assertion.check().isNotNull(predictionProba);
		//---
		this.predictionProba = predictionProba;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Explanation'.
	 * @return DtList de Explanation explanation
	 */
	@Field(smartType = "STyDtExplanation", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Explanation2D")
	public List<List<Double>> getExplanation2D() {
		return explanation2D;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Explanation2D'.
	 * @param explanation DtList de Explanation2D
	 */
	public void setExplanation2D(final List<List<Double>> explanation2D) {
		io.vertigo.core.lang.Assertion.check().isNotNull(explanation2D);
		//---
		this.explanation2D = explanation2D;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Explanation1D'.
	 * @return DtList de Explanation explanation1D
	 */
	@Field(smartType = "STyPredictionNumeric", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Explanation1D")
	public java.util.List<java.math.BigDecimal> getExplanation1D() {
		return explanation1D;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Explanation2D'.
	 * @param explanation DtList de Explanation2D
	 */
	public void setExplanation1D(final java.util.List<java.math.BigDecimal> explanation1D) {
		io.vertigo.core.lang.Assertion.check().isNotNull(explanation1D);
		//---
		this.explanation1D = explanation1D;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
