package io.vertigo.ai.predict.models;

import java.util.ArrayList;
import java.util.List;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Predict implements DtObject {
	private static final long serialVersionUID = 1L;

	private String predictionLabel;
	private java.math.BigDecimal predictionNumeric;
	private java.util.List<java.math.BigDecimal> predictionProba = new java.util.ArrayList<>();
	private List<List<Double>> explanation =  new ArrayList<List<Double>>();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction Label'.
	 * @return String predictionLabel
	 */
	@Field(smartType = "STyPredictionLabel", label = "Prediction Label")
	public String getPredictionLabel() {
		return predictionLabel;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction Label'.
	 * @param predictionLabel String
	 */
	public void setPredictionLabel(final String predictionLabel) {
		this.predictionLabel = predictionLabel;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Numeric Prediction'.
	 * @return BigDecimal predictionNumeric
	 */
	@Field(smartType = "STyPredictionNumeric", label = "Numeric Prediction")
	public java.math.BigDecimal getPredictionNumeric() {
		return predictionNumeric;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Numeric Prediction'.
	 * @param predictionNumeric BigDecimal
	 */
	public void setPredictionNumeric(final java.math.BigDecimal predictionNumeric) {
		this.predictionNumeric = predictionNumeric;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction Probability'.
	 * @return List de BigDecimal predictionProba
	 */
	@Field(smartType = "STyPredictionNumeric", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Prediction Probability")
	public java.util.List<java.math.BigDecimal> getPredictionProba() {
		return predictionProba;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction Probability'.
	 * @param predictionProba List de BigDecimal
	 */
	public void setPredictionProba(final java.util.List<java.math.BigDecimal> predictionProba) {
		io.vertigo.core.lang.Assertion.check().isNotNull(predictionProba);
		//---
		this.predictionProba = predictionProba;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Explanation'.
	 * @return DtList de Explanation explanation
	 */
	@Field(smartType = "STyDtExplanation", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Explanation")
	public List<List<Double>> getExplanation() {
		return explanation;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Explanation'.
	 * @param explanation DtList de Explanation
	 */
	public void setExplanation(final List<List<Double>> explanation) {
		io.vertigo.core.lang.Assertion.check().isNotNull(explanation);
		//---
		this.explanation = explanation;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
