package io.vertigo.ai.predict.models;

import java.util.ArrayList;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class PredictResponse implements DtObject {
	private static final long serialVersionUID = 1L;

	private java.util.List<io.vertigo.ai.predict.models.Predict> predictionList =  new ArrayList<>();
	private String error =  new String();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction List'.
	 * @return DtList de Predict predictionList
	 */
	@Field(smartType = "STyDtPredict", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Prediction List")
	public java.util.List<io.vertigo.ai.predict.models.Predict> getPredictionList() {
		return predictionList;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction List'.
	 * @param predictionList DtList de Predict
	 */
	public void setPredictionList(final java.util.List<io.vertigo.ai.predict.models.Predict> predictionList) {
		io.vertigo.core.lang.Assertion.check().isNotNull(predictionList);
		//---
		this.predictionList = predictionList;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction Error'.
	 * @return error String
	 */
	@Field(smartType = "STyPredictionLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Prediction Erro")
	public String getError() {
		return error;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction Error'.
	 * @param error String
	 */
	public void setError(final String error) {
		//---
		this.error = error;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
