package io.vertigo.ai.example.heroes.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
@io.vertigo.datamodel.structure.stereotype.DataSpace("train")
public final class Era implements Entity {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Integer eraId;
	private String eraName;

	/** {@inheritDoc} */
	@Override
	public UID<Era> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'ID'.
	 * @return Integer id <b>Obligatoire</b>
	 */
	@Field(smartType = "STyInt", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "ID")
	public Integer getId() {
		return id;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'ID'.
	 * @param id Integer <b>Obligatoire</b>
	 */
	public void setId(final Integer id) {
		this.id = id;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Era ID'.
	 * @return Integer eraId
	 */
	@Field(smartType = "STyInt", label = "Era ID")
	public Integer getEraId() {
		return eraId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Era ID'.
	 * @param eraId Integer
	 */
	public void setEraId(final Integer eraId) {
		this.eraId = eraId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Name'.
	 * @return String eraName <b>Obligatoire</b>
	 */
	@Field(smartType = "STyString", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Name")
	public String getEraName() {
		return eraName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Name'.
	 * @param eraName String <b>Obligatoire</b>
	 */
	public void setEraName(final String eraName) {
		this.eraName = eraName;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
