package io.vertigo.ai.example.heroes.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.Entity;
import io.vertigo.datamodel.structure.model.UID;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
@io.vertigo.datamodel.structure.stereotype.DataSpace("train")
public final class FactionCount implements Entity {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private String factionName;
	private Integer countFactionName;

	/** {@inheritDoc} */
	@Override
	public UID<FactionCount> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'ID'.
	 * @return Integer id <b>Obligatoire</b>
	 */
	@Field(smartType = "STyInt", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "ID")
	public Integer getId() {
		return id;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'ID'.
	 * @param id Integer <b>Obligatoire</b>
	 */
	public void setId(final Integer id) {
		this.id = id;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Name'.
	 * @return String factionName <b>Obligatoire</b>
	 */
	@Field(smartType = "STyString", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Name")
	public String getFactionName() {
		return factionName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Name'.
	 * @param factionName String <b>Obligatoire</b>
	 */
	public void setFactionName(final String factionName) {
		this.factionName = factionName;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Heroes per faction'.
	 * @return Integer countFactionName <b>Obligatoire</b>
	 */
	@Field(smartType = "STyInt", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Heroes per faction")
	public Integer getCountFactionName() {
		return countFactionName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Heroes per faction'.
	 * @param countFactionName Integer <b>Obligatoire</b>
	 */
	public void setCountFactionName(final Integer countFactionName) {
		this.countFactionName = countFactionName;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
