resources: 
  - { type: kpr, path: src/test/resources/io/vertigo/ai/example/telstra/module.kpr}
mdaConfig:
  projectPackageName: io.vertigo.ai.example
  targetGenDir : src/test/
  properties: 
    vertigo.domain.java: true
    vertigo.domain.java.generateDtResources: false
    vertigo.domain.sql: true
    vertigo.domain.sql.targetSubDir: javagen/sqlgen
    vertigo.domain.sql.baseCible: H2
    vertigo.domain.sql.generateDrop: true
    vertigo.domain.sql.generateMasterData: true
    vertigo.task: true
