package io.vertigo.ai.train.domain;

import java.util.Arrays;
import java.util.Iterator;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.definitions.DtFieldName;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DtDefinitions implements Iterable<Class<?>> {

	/**
	 * Enumération des DtDefinitions.
	 */
	public enum Definitions {
		/** Objet de données DeployPredict. */
		DeployPredict(io.vertigo.ai.train.models.DeployPredict.class),
		/** Objet de données Score. */
		Score(io.vertigo.ai.train.models.ScoreResponse.class),
		/** Objet de données TrainResponse. */
		TrainResponse(io.vertigo.ai.train.models.TrainResponse.class)		;

		private final Class<?> clazz;

		private Definitions(final Class<?> clazz) {
			this.clazz = clazz;
		}

		/** 
		 * Classe associée.
		 * @return Class d'implémentation de l'objet 
		 */
		public Class<?> getDtClass() {
			return clazz;
		}
	}

	/**
	 * Enumération des champs de DeployPredict.
	 */
	public enum DeployPredictFields implements DtFieldName<io.vertigo.ai.train.models.DeployPredict> {
		/** Propriété 'Status'. */
		status,
		/** Propriété 'Response'. */
		response	}

	/**
	 * Enumération des champs de Score.
	 */
	public enum ScoreFields implements DtFieldName<io.vertigo.ai.train.models.ScoreResponse> {
		/** Propriété 'Model name'. */
		modelName,
		/** Propriété 'Model version'. */
		version,
		/** Propriété 'Model score'. */
		score	}

	/**
	 * Enumération des champs de TrainResponse.
	 */
	public enum TrainResponseFields implements DtFieldName<io.vertigo.ai.train.models.TrainResponse> {
		/** Propriété 'Request duration'. */
		time,
		/** Propriété 'Model name'. */
		modelName,
		/** Propriété 'Model version'. */
		version,
		/** Propriété 'Model score'. */
		score,
		/** Propriété 'Status'. */
		status,
		/** Propriété 'Response'. */
		response,
		/** Propriété 'Deploy to prediction'. */
		deploy	}

	/** {@inheritDoc} */
	@Override
	public Iterator<Class<?>> iterator() {
		return new Iterator<>() {
			private Iterator<Definitions> it = Arrays.asList(Definitions.values()).iterator();

			/** {@inheritDoc} */
			@Override
			public boolean hasNext() {
				return it.hasNext();
			}

			/** {@inheritDoc} */
			@Override
			public Class<?> next() {
				return it.next().getDtClass();
			}
		};
	}
}
