package io.vertigo.ai.server.models;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DeployResponse implements DtObject {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private String name;
	private Integer version;
	private Boolean activated;
	private Boolean auto;
	private String error;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Model ID'.
	 * @return Integer id <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPredictionInteger", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Model ID")
	public Integer getId() {
		return id;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Model ID'.
	 * @param id Integer <b>Obligatoire</b>
	 */
	public void setId(final Integer id) {
		this.id = id;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Model name'.
	 * @return String name <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPredictionLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Model name")
	public String getName() {
		return name;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Model name'.
	 * @param name String <b>Obligatoire</b>
	 */
	public void setName(final String name) {
		this.name = name;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Model version'.
	 * @return Integer version <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPredictionInteger", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Model version")
	public Integer getVersion() {
		return version;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Model version'.
	 * @param version Integer <b>Obligatoire</b>
	 */
	public void setVersion(final Integer version) {
		this.version = version;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Model is activated'.
	 * @return Boolean activated <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPredictionBoolean", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Model is activated")
	public Boolean getActivated() {
		return activated;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Model is activated'.
	 * @param activated Boolean <b>Obligatoire</b>
	 */
	public void setActivated(final Boolean activated) {
		this.activated = activated;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Model is auto deployed'.
	 * @return Boolean auto <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPredictionBoolean", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Model is auto deployed")
	public Boolean getAuto() {
		return auto;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Model is auto deployed'.
	 * @param auto Boolean <b>Obligatoire</b>
	 */
	public void setAuto(final Boolean auto) {
		this.auto = auto;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Error message'.
	 * @return String error <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPredictionLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Error message")
	public String getError() {
		return error;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Error message'.
	 * @param error String <b>Obligatoire</b>
	 */
	public void setError(final String error) {
		this.error = error;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
