package io.vertigo.ai.server.models;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Predict implements DtObject {
	private static final long serialVersionUID = 1L;

	private String predictionLabel;
	private java.math.BigDecimal predictionNumeric;
	private java.util.List<java.math.BigDecimal> predictionVector = new java.util.ArrayList<>();
	private java.util.List<java.math.BigDecimal> predictionProba = new java.util.ArrayList<>();
	private java.util.List<java.math.BigDecimal> explanation1D;
	private java.util.List<java.util.List<java.math.BigDecimal>> explanation2D =  new  java.util.ArrayList<>();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction label'.
	 * @return String predictionLabel <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPredictionLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Prediction label")
	public String getPredictionLabel() {
		return predictionLabel;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction label'.
	 * @param predictionLabel String <b>Obligatoire</b>
	 */
	public void setPredictionLabel(final String predictionLabel) {
		this.predictionLabel = predictionLabel;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction numeric'.
	 * @return BigDecimal predictionNumeric <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPredictionNumeric", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Prediction numeric")
	public java.math.BigDecimal getPredictionNumeric() {
		return predictionNumeric;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction numeric'.
	 * @param predictionNumeric BigDecimal <b>Obligatoire</b>
	 */
	public void setPredictionNumeric(final java.math.BigDecimal predictionNumeric) {
		this.predictionNumeric = predictionNumeric;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction vector'.
	 * @return List de BigDecimal predictionVector
	 */
	@Field(smartType = "STyPredictionNumeric", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Prediction vector")
	public java.util.List<java.math.BigDecimal> getPredictionVector() {
		return predictionVector;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction vector'.
	 * @param predictionVector List de BigDecimal
	 */
	public void setPredictionVector(final java.util.List<java.math.BigDecimal> predictionVector) {
		io.vertigo.core.lang.Assertion.check().isNotNull(predictionVector);
		//---
		this.predictionVector = predictionVector;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction probabilities'.
	 * @return List de BigDecimal predictionProba
	 */
	@Field(smartType = "STyPredictionNumeric", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Prediction probabilities")
	public java.util.List<java.math.BigDecimal> getPredictionProba() {
		return predictionProba;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction probabilities'.
	 * @param predictionProba List de BigDecimal
	 */
	public void setPredictionProba(final java.util.List<java.math.BigDecimal> predictionProba) {
		io.vertigo.core.lang.Assertion.check().isNotNull(predictionProba);
		//---
		this.predictionProba = predictionProba;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété '1D Explanation'.
	 * @return Explanation explanation1D <b>Obligatoire</b>
	 */
	@Field(smartType = "STyDtExplanation", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "1D Explanation")
	public java.util.List<java.math.BigDecimal> getExplanation1D() {
		return explanation1D;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété '1D Explanation'.
	 * @param explanation1D Explanation <b>Obligatoire</b>
	 */
	public void setExplanation1D(final java.util.List<java.math.BigDecimal> explanation1D) {
		this.explanation1D = explanation1D;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété '2D Explanation'.
	 * @return DtList de Explanation explanation2D
	 */
	@Field(smartType = "STyDtExplanation", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "2D Explanation")
	public java.util.List<java.util.List<java.math.BigDecimal>> getExplanation2D() {
		return explanation2D;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété '2D Explanation'.
	 * @param explanation2D DtList de Explanation
	 */
	public void setExplanation2D(final java.util.List<java.util.List<java.math.BigDecimal>> explanation2D) {
		io.vertigo.core.lang.Assertion.check().isNotNull(explanation2D);
		//---
		this.explanation2D = explanation2D;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
