package io.vertigo.ai.example.data.models;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class LogFeature implements DtObject {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private String logFeature;
	private Integer volume;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'ID'.
	 * @return Integer id <b>Obligatoire</b>
	 */
	@Field(smartType = "STyInteger", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "ID")
	public Integer getId() {
		return id;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'ID'.
	 * @param id Integer <b>Obligatoire</b>
	 */
	public void setId(final Integer id) {
		this.id = id;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Log Feature'.
	 * @return String logFeature <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Log Feature")
	public String getLogFeature() {
		return logFeature;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Log Feature'.
	 * @param logFeature String <b>Obligatoire</b>
	 */
	public void setLogFeature(final String logFeature) {
		this.logFeature = logFeature;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Volume'.
	 * @return Integer volume <b>Obligatoire</b>
	 */
	@Field(smartType = "STyInteger", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Volume")
	public Integer getVolume() {
		return volume;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Volume'.
	 * @param volume Integer <b>Obligatoire</b>
	 */
	public void setVolume(final Integer volume) {
		this.volume = volume;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
