package io.vertigo.ai.example.telstra.dao;

import javax.inject.Inject;

import io.vertigo.core.lang.Generated;
import io.vertigo.core.node.Node;
import io.vertigo.datamodel.task.definitions.TaskDefinition;
import io.vertigo.datamodel.task.model.Task;
import io.vertigo.datamodel.task.model.TaskBuilder;
import io.vertigo.datastore.entitystore.EntityStoreManager;
import io.vertigo.datastore.impl.dao.DAO;
import io.vertigo.datastore.impl.dao.StoreServices;
import io.vertigo.datamodel.smarttype.SmartTypeManager;
import io.vertigo.datamodel.task.TaskManager;
import io.vertigo.ai.example.telstra.domain.LogFeatureTrain;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class LogFeatureTrainDAO extends DAO<LogFeatureTrain, java.lang.Long> implements StoreServices {

	/**
	 * Contructeur.
	 * @param entityStoreManager Manager de persistance
	 * @param taskManager Manager de Task
	 * @param smartTypeManager SmartTypeManager
	 */
	@Inject
	public LogFeatureTrainDAO(final EntityStoreManager entityStoreManager, final TaskManager taskManager, final SmartTypeManager smartTypeManager) {
		super(LogFeatureTrain.class, entityStoreManager, taskManager, smartTypeManager);
	}


	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Node.getNode().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkBulkCreateLogFeatureTrain.
	 * @param logFeatureTrainList DtList de LogFeatureTrain
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			dataSpace = "train",
			name = "TkBulkCreateLogFeatureTrain",
			request = "INSERT INTO LOG_FEATURE_TRAIN (ID, CODE, LOG_FEATURE, VOLUME) values (#logFeatureTrainList.id#, #logFeatureTrainList.code#, #logFeatureTrainList.logFeature#, #logFeatureTrainList.volume#)",
			taskEngineClass = io.vertigo.basics.task.TaskEngineProcBatch.class)
	public void bulkCreateLogFeatureTrain(@io.vertigo.datamodel.task.proxy.TaskInput(name = "logFeatureTrainList", smartType = "STyDtLogFeatureTrain") final io.vertigo.datamodel.structure.model.DtList<io.vertigo.ai.example.telstra.domain.LogFeatureTrain> logFeatureTrainList) {
		final Task task = createTaskBuilder("TkBulkCreateLogFeatureTrain")
				.addValue("logFeatureTrainList", logFeatureTrainList)
				.addContextProperty("connectionName", io.vertigo.datastore.impl.dao.StoreUtil.getConnectionName("train"))
				.build();
		getTaskManager().execute(task);
	}

	/**
	 * Execute la tache TkLoadLogFeature.
	 * @param logFeatureIds List de Long
	 * @return DtList de LogFeatureTrain dtcLogFeatureTrain
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkLoadLogFeature",
			request = "select * from LOG_FEATURE where ID in (#logFeatureIds.rownum#);",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyDtLogFeatureTrain")
	public io.vertigo.datamodel.structure.model.DtList<io.vertigo.ai.example.telstra.domain.LogFeatureTrain> loadLogFeature(@io.vertigo.datamodel.task.proxy.TaskInput(name = "logFeatureIds", smartType = "STyId") final java.util.List<Long> logFeatureIds) {
		final Task task = createTaskBuilder("TkLoadLogFeature")
				.addValue("logFeatureIds", logFeatureIds)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

}
