package io.vertigo.ai.example.telstra.dao;

import javax.inject.Inject;

import io.vertigo.core.lang.Generated;
import io.vertigo.core.node.Node;
import io.vertigo.datamodel.task.definitions.TaskDefinition;
import io.vertigo.datamodel.task.model.Task;
import io.vertigo.datamodel.task.model.TaskBuilder;
import io.vertigo.datastore.entitystore.EntityStoreManager;
import io.vertigo.datastore.impl.dao.DAO;
import io.vertigo.datastore.impl.dao.StoreServices;
import io.vertigo.datamodel.smarttype.SmartTypeManager;
import io.vertigo.datamodel.task.TaskManager;
import io.vertigo.ai.example.telstra.domain.SeverityTypeTrain;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class SeverityTypeTrainDAO extends DAO<SeverityTypeTrain, java.lang.Long> implements StoreServices {

	/**
	 * Contructeur.
	 * @param entityStoreManager Manager de persistance
	 * @param taskManager Manager de Task
	 * @param smartTypeManager SmartTypeManager
	 */
	@Inject
	public SeverityTypeTrainDAO(final EntityStoreManager entityStoreManager, final TaskManager taskManager, final SmartTypeManager smartTypeManager) {
		super(SeverityTypeTrain.class, entityStoreManager, taskManager, smartTypeManager);
	}


	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Node.getNode().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkBulkCreateSeverityTypeTrain.
	 * @param severityTypeTrainList DtList de SeverityTypeTrain
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			dataSpace = "train",
			name = "TkBulkCreateSeverityTypeTrain",
			request = "INSERT INTO SEVERITY_TYPE_TRAIN (ID, CODE, SEVERITY_TYPE) values (#severityTypeTrainList.id#, #severityTypeTrainList.code#, #severityTypeTrainList.severityType#)",
			taskEngineClass = io.vertigo.basics.task.TaskEngineProcBatch.class)
	public void bulkCreateSeverityTypeTrain(@io.vertigo.datamodel.task.proxy.TaskInput(name = "severityTypeTrainList", smartType = "STyDtSeverityTypeTrain") final io.vertigo.datamodel.structure.model.DtList<io.vertigo.ai.example.telstra.domain.SeverityTypeTrain> severityTypeTrainList) {
		final Task task = createTaskBuilder("TkBulkCreateSeverityTypeTrain")
				.addValue("severityTypeTrainList", severityTypeTrainList)
				.addContextProperty("connectionName", io.vertigo.datastore.impl.dao.StoreUtil.getConnectionName("train"))
				.build();
		getTaskManager().execute(task);
	}

	/**
	 * Execute la tache TkLoadSeverityType.
	 * @param severityTypeIds List de Long
	 * @return DtList de SeverityTypeTrain dtcSeverityTypeTrain
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkLoadSeverityType",
			request = "select * from SEVERITY_TYPE where ID in (#severityTypeIds.rownum#);",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyDtSeverityTypeTrain")
	public io.vertigo.datamodel.structure.model.DtList<io.vertigo.ai.example.telstra.domain.SeverityTypeTrain> loadSeverityType(@io.vertigo.datamodel.task.proxy.TaskInput(name = "severityTypeIds", smartType = "STyId") final java.util.List<Long> severityTypeIds) {
		final Task task = createTaskBuilder("TkLoadSeverityType")
				.addValue("severityTypeIds", severityTypeIds)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

}
