package io.vertigo.ai.server.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DeployResponse implements DtObject {
	private static final long serialVersionUID = 1L;

	private Integer id;
	private String name;
	private Integer version;
	private Boolean activated;
	private Boolean auto;
	private String error;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'ID'.
	 * @return Integer id <b>Obligatoire</b>
	 */
	@Field(smartType = "STyIntegerAIResponse", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "ID")
	public Integer getId() {
		return id;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'ID'.
	 * @param id Integer <b>Obligatoire</b>
	 */
	public void setId(final Integer id) {
		this.id = id;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Name'.
	 * @return String name <b>Obligatoire</b>
	 */
	@Field(smartType = "STyStringAIResponse", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Name")
	public String getName() {
		return name;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Name'.
	 * @param name String <b>Obligatoire</b>
	 */
	public void setName(final String name) {
		this.name = name;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Version'.
	 * @return Integer version <b>Obligatoire</b>
	 */
	@Field(smartType = "STyIntegerAIResponse", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Version")
	public Integer getVersion() {
		return version;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Version'.
	 * @param version Integer <b>Obligatoire</b>
	 */
	public void setVersion(final Integer version) {
		this.version = version;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Activated'.
	 * @return Boolean activated <b>Obligatoire</b>
	 */
	@Field(smartType = "STyBooleanAIResponse", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Activated")
	public Boolean getActivated() {
		return activated;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Activated'.
	 * @param activated Boolean <b>Obligatoire</b>
	 */
	public void setActivated(final Boolean activated) {
		this.activated = activated;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Auto'.
	 * @return Boolean auto <b>Obligatoire</b>
	 */
	@Field(smartType = "STyBooleanAIResponse", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Auto")
	public Boolean getAuto() {
		return auto;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Auto'.
	 * @param auto Boolean <b>Obligatoire</b>
	 */
	public void setAuto(final Boolean auto) {
		this.auto = auto;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Error'.
	 * @return String error <b>Obligatoire</b>
	 */
	@Field(smartType = "STyStringAIResponse", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Error")
	public String getError() {
		return error;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Error'.
	 * @param error String <b>Obligatoire</b>
	 */
	public void setError(final String error) {
		this.error = error;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
