package io.vertigo.ai.server.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class PredictResponse implements DtObject {
	private static final long serialVersionUID = 1L;

	private io.vertigo.datamodel.structure.model.DtList<io.vertigo.ai.server.domain.Predict> predictionList =  new io.vertigo.datamodel.structure.model.DtList<>(io.vertigo.ai.server.domain.Predict.class);
	private String error;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prediction List'.
	 * @return DtList de Predict predictionList
	 */
	@Field(smartType = "STyDtPredict", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Prediction List")
	public io.vertigo.datamodel.structure.model.DtList<io.vertigo.ai.server.domain.Predict> getPredictionList() {
		return predictionList;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prediction List'.
	 * @param predictionList DtList de Predict
	 */
	public void setPredictionList(final io.vertigo.datamodel.structure.model.DtList<io.vertigo.ai.server.domain.Predict> predictionList) {
		io.vertigo.core.lang.Assertion.check().isNotNull(predictionList);
		//---
		this.predictionList = predictionList;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Error'.
	 * @return String error <b>Obligatoire</b>
	 */
	@Field(smartType = "STyStringAIResponse", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Error")
	public String getError() {
		return error;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Error'.
	 * @param error String <b>Obligatoire</b>
	 */
	public void setError(final String error) {
		this.error = error;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
