package io.vertigo.ai.example.domain;

import java.util.Arrays;
import java.util.Iterator;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.definitions.DtFieldName;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DtDefinitions implements Iterable<Class<?>> {

	/**
	 * Enumération des DtDefinitions.
	 */
	public enum Definitions {
		/** Objet de données DeployPredict. */
		DeployPredict(io.vertigo.ai.server.domain.DeployPredict.class),
		/** Objet de données DeployResponse. */
		DeployResponse(io.vertigo.ai.server.domain.DeployResponse.class),
		/** Objet de données Era. */
		Era(io.vertigo.ai.example.heroes.domain.Era.class),
		/** Objet de données EventType. */
		EventType(io.vertigo.ai.example.telstra.domain.EventType.class),
		/** Objet de données Explanation. */
		Explanation(io.vertigo.ai.server.domain.Explanation.class),
		/** Objet de données Faction. */
		Faction(io.vertigo.ai.example.heroes.domain.Faction.class),
		/** Objet de données Heroe. */
		Heroe(io.vertigo.ai.example.heroes.domain.Heroe.class),
		/** Objet de données Iris. */
		Iris(io.vertigo.ai.example.iris.domain.Iris.class),
		/** Objet de données IrisTrain. */
		IrisTrain(io.vertigo.ai.example.iris.domain.IrisTrain.class),
		/** Objet de données Location. */
		Location(io.vertigo.ai.example.telstra.domain.Location.class),
		/** Objet de données LogFeature. */
		LogFeature(io.vertigo.ai.example.telstra.domain.LogFeature.class),
		/** Objet de données Predict. */
		Predict(io.vertigo.ai.server.domain.Predict.class),
		/** Objet de données PredictResponse. */
		PredictResponse(io.vertigo.ai.server.domain.PredictResponse.class),
		/** Objet de données ResourceType. */
		ResourceType(io.vertigo.ai.example.telstra.domain.ResourceType.class),
		/** Objet de données Score. */
		Score(io.vertigo.ai.server.domain.Score.class),
		/** Objet de données ScoreResponse. */
		ScoreResponse(io.vertigo.ai.server.domain.ScoreResponse.class),
		/** Objet de données SeverityType. */
		SeverityType(io.vertigo.ai.example.telstra.domain.SeverityType.class),
		/** Objet de données TrainResponse. */
		TrainResponse(io.vertigo.ai.server.domain.TrainResponse.class)		;

		private final Class<?> clazz;

		private Definitions(final Class<?> clazz) {
			this.clazz = clazz;
		}

		/** 
		 * Classe associée.
		 * @return Class d'implémentation de l'objet 
		 */
		public Class<?> getDtClass() {
			return clazz;
		}
	}

	/**
	 * Enumération des champs de DeployPredict.
	 */
	public enum DeployPredictFields implements DtFieldName<io.vertigo.ai.server.domain.DeployPredict> {
		/** Propriété 'Status'. */
		status,
		/** Propriété 'Response'. */
		response	}

	/**
	 * Enumération des champs de DeployResponse.
	 */
	public enum DeployResponseFields implements DtFieldName<io.vertigo.ai.server.domain.DeployResponse> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Name'. */
		name,
		/** Propriété 'Version'. */
		version,
		/** Propriété 'Activated'. */
		activated,
		/** Propriété 'Auto'. */
		auto,
		/** Propriété 'Error'. */
		error	}

	/**
	 * Enumération des champs de Era.
	 */
	public enum EraFields implements DtFieldName<io.vertigo.ai.example.heroes.domain.Era> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Name'. */
		name	}

	/**
	 * Enumération des champs de EventType.
	 */
	public enum EventTypeFields implements DtFieldName<io.vertigo.ai.example.telstra.domain.EventType> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Event Type'. */
		eventType	}

	/**
	 * Enumération des champs de Explanation.
	 */
	public enum ExplanationFields implements DtFieldName<io.vertigo.ai.server.domain.Explanation> {
		/** Propriété 'Explanation 1D'. */
		explainFeature	}

	/**
	 * Enumération des champs de Faction.
	 */
	public enum FactionFields implements DtFieldName<io.vertigo.ai.example.heroes.domain.Faction> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Name'. */
		name,
		/** Propriété 'Era ID'. */
		era	}

	/**
	 * Enumération des champs de Heroe.
	 */
	public enum HeroeFields implements DtFieldName<io.vertigo.ai.example.heroes.domain.Heroe> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Name'. */
		name,
		/** Propriété 'Job'. */
		job,
		/** Propriété 'Faction ID'. */
		faction	}

	/**
	 * Enumération des champs de Iris.
	 */
	public enum IrisFields implements DtFieldName<io.vertigo.ai.example.iris.domain.Iris> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Sepal Lenght'. */
		sepalLength,
		/** Propriété 'Sepal Width'. */
		sepalWidth,
		/** Propriété 'Petal Lenght'. */
		petalLength,
		/** Propriété 'Petal Width'. */
		petalWidth,
		/** Propriété 'Label'. */
		variety	}

	/**
	 * Enumération des champs de IrisTrain.
	 */
	public enum IrisTrainFields implements DtFieldName<io.vertigo.ai.example.iris.domain.IrisTrain> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Sepal Lenght'. */
		sepalLength,
		/** Propriété 'Sepal Width'. */
		sepalWidth,
		/** Propriété 'Petal Lenght'. */
		petalLength,
		/** Propriété 'Petal Width'. */
		petalWidth,
		/** Propriété 'Label'. */
		variety	}

	/**
	 * Enumération des champs de Location.
	 */
	public enum LocationFields implements DtFieldName<io.vertigo.ai.example.telstra.domain.Location> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Location'. */
		location,
		/** Propriété 'Severity Fault'. */
		severityFault	}

	/**
	 * Enumération des champs de LogFeature.
	 */
	public enum LogFeatureFields implements DtFieldName<io.vertigo.ai.example.telstra.domain.LogFeature> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Log Feature'. */
		logFeature,
		/** Propriété 'Volume'. */
		volume	}

	/**
	 * Enumération des champs de Predict.
	 */
	public enum PredictFields implements DtFieldName<io.vertigo.ai.server.domain.Predict> {
		/** Propriété 'Prediction Label'. */
		predictionLabel,
		/** Propriété 'Prediction Numeric'. */
		predictionNumeric,
		/** Propriété 'Prediction Vector'. */
		predictionNVector,
		/** Propriété 'Exploration 1D'. */
		explantion1D,
		/** Propriété 'Exploration 2D'. */
		explantion2D	}

	/**
	 * Enumération des champs de PredictResponse.
	 */
	public enum PredictResponseFields implements DtFieldName<io.vertigo.ai.server.domain.PredictResponse> {
		/** Propriété 'Prediction List'. */
		predictionList,
		/** Propriété 'Error'. */
		error	}

	/**
	 * Enumération des champs de ResourceType.
	 */
	public enum ResourceTypeFields implements DtFieldName<io.vertigo.ai.example.telstra.domain.ResourceType> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Resource Type'. */
		resourceType	}

	/**
	 * Enumération des champs de Score.
	 */
	public enum ScoreFields implements DtFieldName<io.vertigo.ai.server.domain.Score> {
		/** Propriété 'Score Mean'. */
		scoreMean,
		/** Propriété 'Score Standard deviation'. */
		scoreStd	}

	/**
	 * Enumération des champs de ScoreResponse.
	 */
	public enum ScoreResponseFields implements DtFieldName<io.vertigo.ai.server.domain.ScoreResponse> {
		/** Propriété 'time'. */
		time,
		/** Propriété 'Name'. */
		modelName,
		/** Propriété 'Version'. */
		version,
		/** Propriété 'Score'. */
		score,
		/** Propriété 'Status'. */
		status	}

	/**
	 * Enumération des champs de SeverityType.
	 */
	public enum SeverityTypeFields implements DtFieldName<io.vertigo.ai.example.telstra.domain.SeverityType> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Severity Type'. */
		severityType	}

	/**
	 * Enumération des champs de TrainResponse.
	 */
	public enum TrainResponseFields implements DtFieldName<io.vertigo.ai.server.domain.TrainResponse> {
		/** Propriété 'time'. */
		time,
		/** Propriété 'Name'. */
		modelName,
		/** Propriété 'Version'. */
		version,
		/** Propriété 'Score'. */
		score,
		/** Propriété 'Status'. */
		status,
		/** Propriété 'Response'. */
		response,
		/** Propriété 'Deploy'. */
		deploy	}

	/** {@inheritDoc} */
	@Override
	public Iterator<Class<?>> iterator() {
		return new Iterator<>() {
			private Iterator<Definitions> it = Arrays.asList(Definitions.values()).iterator();

			/** {@inheritDoc} */
			@Override
			public boolean hasNext() {
				return it.hasNext();
			}

			/** {@inheritDoc} */
			@Override
			public Class<?> next() {
				return it.next().getDtClass();
			}
		};
	}
}
