package io.vertigo.ai.example.domain;

import java.util.Arrays;
import java.util.Iterator;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.definitions.DtFieldName;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DtDefinitions implements Iterable<Class<?>> {

	/**
	 * Enumération des DtDefinitions.
	 */
	public enum Definitions {
		/** Objet de données EventType. */
		EventType(io.vertigo.ai.example.telstra.domain.EventType.class),
		/** Objet de données Iris. */
		Iris(io.vertigo.ai.example.iris.domain.Iris.class),
		/** Objet de données IrisTrain. */
		IrisTrain(io.vertigo.ai.example.iris.domain.IrisTrain.class),
		/** Objet de données Location. */
		Location(io.vertigo.ai.example.telstra.domain.Location.class),
		/** Objet de données LogFeature. */
		LogFeature(io.vertigo.ai.example.telstra.domain.LogFeature.class),
		/** Objet de données ResourceType. */
		ResourceType(io.vertigo.ai.example.telstra.domain.ResourceType.class),
		/** Objet de données SeverityType. */
		SeverityType(io.vertigo.ai.example.telstra.domain.SeverityType.class)		;

		private final Class<?> clazz;

		private Definitions(final Class<?> clazz) {
			this.clazz = clazz;
		}

		/** 
		 * Classe associée.
		 * @return Class d'implémentation de l'objet 
		 */
		public Class<?> getDtClass() {
			return clazz;
		}
	}

	/**
	 * Enumération des champs de EventType.
	 */
	public enum EventTypeFields implements DtFieldName<io.vertigo.ai.example.telstra.domain.EventType> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Event Type'. */
		eventType	}

	/**
	 * Enumération des champs de Iris.
	 */
	public enum IrisFields implements DtFieldName<io.vertigo.ai.example.iris.domain.Iris> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Sepal Lenght'. */
		sepalLength,
		/** Propriété 'Sepal Width'. */
		sepalWidth,
		/** Propriété 'Petal Lenght'. */
		petalLength,
		/** Propriété 'Petal Width'. */
		petalWidth,
		/** Propriété 'Label'. */
		variety	}

	/**
	 * Enumération des champs de IrisTrain.
	 */
	public enum IrisTrainFields implements DtFieldName<io.vertigo.ai.example.iris.domain.IrisTrain> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Sepal Lenght'. */
		sepalLength,
		/** Propriété 'Sepal Width'. */
		sepalWidth,
		/** Propriété 'Petal Lenght'. */
		petalLength,
		/** Propriété 'Petal Width'. */
		petalWidth,
		/** Propriété 'Label'. */
		variety	}

	/**
	 * Enumération des champs de Location.
	 */
	public enum LocationFields implements DtFieldName<io.vertigo.ai.example.telstra.domain.Location> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Location'. */
		location,
		/** Propriété 'Severity Fault'. */
		severityFault	}

	/**
	 * Enumération des champs de LogFeature.
	 */
	public enum LogFeatureFields implements DtFieldName<io.vertigo.ai.example.telstra.domain.LogFeature> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Log Feature'. */
		logFeature,
		/** Propriété 'Volume'. */
		volume	}

	/**
	 * Enumération des champs de ResourceType.
	 */
	public enum ResourceTypeFields implements DtFieldName<io.vertigo.ai.example.telstra.domain.ResourceType> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Resource Type'. */
		resourceType	}

	/**
	 * Enumération des champs de SeverityType.
	 */
	public enum SeverityTypeFields implements DtFieldName<io.vertigo.ai.example.telstra.domain.SeverityType> {
		/** Propriété 'ID'. */
		id,
		/** Propriété 'Severity Type'. */
		severityType	}

	/** {@inheritDoc} */
	@Override
	public Iterator<Class<?>> iterator() {
		return new Iterator<>() {
			private Iterator<Definitions> it = Arrays.asList(Definitions.values()).iterator();

			/** {@inheritDoc} */
			@Override
			public boolean hasNext() {
				return it.hasNext();
			}

			/** {@inheritDoc} */
			@Override
			public Class<?> next() {
				return it.next().getDtClass();
			}
		};
	}
}
